ARM: mcpm: Fix build error with gic_secondary_init call
Commit c0114709ed ("irqchip: gic: Perform the gic_secondary_init()
call via CPU notifier") removed all platform calls to gic_secondary_ini=
t.
Since this file got merged after the removal of the above call, this
function got left out in the current file which is causing the followin=
g
build error:
arch/arm/common/mcpm_platsmp.c:52:2: error: implicit declaration of fun=
ction
=E2=80=98gic_secondary_init=E2=80=99 [-Werror=3Dimplicit-function-decla=
ration]
gic_secondary_init(0);

Signed-off-by: Sachin Kamat <***@linaro.org>
Cc: Catalin Marinas <***@arm.com>
Cc: Nicolas Pitre <***@linaro.org>